apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: ecommerce-namespace
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
