apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-namespace
data:
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"
  MONGODB_DB: OrdersDatabase

  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: eCommerceUsers

  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DB: ecommerceproductsdatabase

  ConnectionStrings__DefaultConnection: "Server=$MYSQL_HOST;Port=$MYSQL_PORT;Database=$MYSQL_DB;User=$MYSQL_USER;Password=$MYSQL_PASSWORD"
  ConnectionStrings__MongoDB: "mongodb://$MONGODB_HOST:$MONGODB_PORT"
  ConnectionStrings__PostgresConnection: "Host=$POSTGRES_HOST;Port=$POSTGRES_PORT;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD"

  UsersMicroservicePort: "8080"
  UsersMicroserviceName: apigateway
  ProductsMicroservicePort: "8080"
  ProductsMicroserviceName: apigateway

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_PRODUCTS_EXCHANGE: products.exchange
  RABBITMQ_USERS_EXCHANGE: users.exchange
