apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ecommerce-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: microecommerceregistry.azurecr.io/ecommerce-mysql:latest
          envFrom:
            - configMapRef:
                name: ecommerce-config
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD

            - name: MYSQL_DATABASE
              value: ecommerceproductsdatabase

          ports:
            - containerPort: 3306
