apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice-deployment
  namespace: ecommerce-namespace
  labels:
    app: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
        - name: users-microservice
          image: microecommerceregistry.azurecr.io/users-microservice:latest
          ports:
            - containerPort: 9090

          # 1) Pull in all your non-sensitive config in one go
          envFrom:
            - configMapRef:
                name: ecommerce-config # must contain POSTGRES_HOST, POSTGRES_PORT ("5432"), POSTGRES_DB

            # 2) Pull in your secrets
            - secretRef:
                name: postgres-credentials # your Secret with POSTGRES_USER & POSTGRES_PASSWORD

          # 3) Override POSTGRES_PORT so it’s just "5432", not "tcp://…"
          env:
            # 4) If you aren’t already, explicitly bring in the user & password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
